//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.manuelmaly.hn;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.TextView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.manuelmaly.hn.R.id;
import com.manuelmaly.hn.R.layout;

public final class AboutActivity_
    extends AboutActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.about);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mHNView = ((TextView) findViewById(id.about_hn));
        mURLView = ((TextView) findViewById(id.about_url));
        mActionbarBack = ((ImageView) findViewById(id.actionbar_back));
        mByView = ((TextView) findViewById(id.about_by));
        mGithubView = ((TextView) findViewById(id.about_github));
        {
            View view = findViewById(id.actionbar_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        backClicked();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static AboutActivity_.IntentBuilder_ intent(Context context) {
        return new AboutActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AboutActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AboutActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
